import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const anakotmai = localFont({
  src: [
    {
      path: "../public/font/Anakotmai-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/font/Anakotmai-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/font/Anakotmai-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-anakotmai",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${anakotmai.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
